services:
  auth-backend:
    image: auth-backend:latest
    ports:
      - "3001:3001"
    environment:
      - IO_URL=http://io-backend:3000
      - JWT_SECRET=IDP2025
    networks:
      - app-network
      - kong-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
          cpus: "1"

networks:
  app-network:
    external: true
  kong-net:
    external: true